describe("commands", function()
  it("retains the public aspect compatibility alias", function()
    local roomplan = require("roomplan")
    assert_equal(roomplan.set_aspect, roomplan.aspect)
  end)

  it("registers idempotently without global maps", function()
    local before = vim.api.nvim_get_keymap("n")
    require("roomplan.commands").register()
    require("roomplan.commands").register()
    assert_equal(vim.fn.exists(":RoomPlanOpen"), 2)
    assert_equal(vim.fn.exists(":RoomPlanSaveAs"), 2)
    assert_equal(vim.fn.exists(":RoomPlanAspect"), 2)
    assert_equal(vim.fn.exists(":RoomPlanCanvasDetail"), 2)
    assert_equal(vim.fn.exists(":RoomPlanRotateView"), 2)
    assert_equal(vim.fn.exists(":RoomPlanAddWindow"), 2)
    assert_equal(vim.fn.exists(":RoomPlanAddOutlet"), 2)
    assert_equal("function", type(require("roomplan").set_canvas_detail))
    assert_equal("function", type(require("roomplan").rotate_view))
    assert_equal("function", type(require("roomplan.controller").add_window))
    assert_equal("function", type(require("roomplan.controller").add_outlet))
    assert_equal(vim.api.nvim_get_keymap("n"), before)
  end)

  it("installs buffer-local W and O mappings for wall features", function()
    require("roomplan.config").reset()
    local bufnr = vim.api.nvim_create_buf(false, true)
    require("roomplan.ui.keymaps").apply(bufnr, { id = "wall-feature-keymaps" })
    local function mapping(lhs)
      return vim.api.nvim_buf_call(bufnr, function()
        return vim.fn.maparg(lhs, "n", false, true)
      end)
    end
    local window = mapping("W")
    local outlet = mapping("O")
    assert_equal("Add RoomPlan window", window.desc)
    assert_equal("function", type(window.callback))
    assert_equal("Add RoomPlan outlet", outlet.desc)
    assert_equal("function", type(outlet.callback))
    assert_true(vim.api.nvim_buf_delete(bufnr, { force = true }) == nil)
  end)

  it("opens the start menu without an active session", function()
    local state = require("roomplan.state")
    local palette = require("roomplan.ui.palette")
    state.reset()

    local menu = assert(require("roomplan.controller").menu(nil))
    local lines = vim.api.nvim_buf_get_lines(menu.bufnr, 0, -1, false)
    assert_equal("Start RoomPlan", lines[1])
    assert_true(palette.close(menu, "test complete"))
  end)

  it("calibrates aspect through command input and the Lua API without a session", function()
    local config = require("roomplan.config")
    config.reset()
    vim.cmd("RoomPlanAspect 1.75")
    assert_equal(1.75, config.get().canvas.cell_aspect)

    local original_input = vim.ui.input
    local prompt
    vim.ui.input = function(opts, done)
      prompt = opts.prompt
      done("2.2")
    end
    local ok, err = xpcall(function() vim.cmd("RoomPlanAspect") end, debug.traceback)
    vim.ui.input = original_input
    if not ok then error(err, 0) end
    assert_true(prompt:match("height/width") ~= nil)
    assert_equal(2.2, config.get().canvas.cell_aspect)

    assert_equal(1.9, require("roomplan").set_aspect(1.9, { quiet = true }))
    assert_equal(1.9, config.get().canvas.cell_aspect)
    config.reset()
  end)
end)
